import component1 from './components/component1';
import component2 from './components/component2';
import component3 from './components/component3';
import component4 from './components/component4';
import component5 from './components/component5';
import component6 from './components/component6';
import component7 from './components/component7';
import component8 from './components/component8';
import component9 from './components/component9';
import component10 from './components/component10';
import component11 from './components/component11';
import component12 from './components/component12';
import component13 from './components/component13';
import component14 from './components/component14';
import component15 from './components/component15';
import component16 from './components/component16';
import component17 from './components/component17';
import component18 from './components/component18';
import component19 from './components/component19';
import component20 from './components/component20';
import component21 from './components/component21';
import component22 from './components/component22';
import component23 from './components/component23';
import component24 from './components/component24';
import component25 from './components/component25';
import component26 from './components/component26';
import component27 from './components/component27';
import component28 from './components/component28';
import component29 from './components/component29';
import component30 from './components/component30';

component1();
component2();
component3();
component4();
component5();
component6();
component7();
component8();
component9();
component10();
component11();
component12();
component13();
component14();
component15();
component16();
component17();
component18();
component19();
component20();
component21();
component22();
component23();
component24();
component25();
component26();
component27();
component28();
component29();
component30();
